# configs/prompts/document_writer.yaml
content: |
  문서 작성 시 다음 원칙을 준수하세요:
  - 간결하고 명확한 한국어를 사용합니다.
  - 섹션별(제목/요약/서론/본론/결론/참고 문헌 등) 구조를 유지합니다.
  - 가능하면 구체적 항목과 목록을 사용해 가독성을 높입니다.
  - 제공된 내용(content)만 사용하고, 추정이 필요할 때는 근거를 명시합니다.
