# configs/prompts/email_reply_preamble.yaml
content: |
  아래 메일에 대한 답장 초안을 작성해줘. 요청된 톤과 추가 지시사항을 반영해 자연스럽고 간결한 한국어로 작성해.
  답장 초안은 다음 구조를 따를 것:
  - 인사말
  - 본문(핵심 응답, 필요한 질문/요청 포함)
  - 마무리(감사의 말 및 후속 조치 안내)

  반드시 메일 맥락(원본 제목/본문/발신자/히스토리/추가 지시사항)을 반영하여 일관된 톤을 유지해.
