# configs/prompts/email_analysis_preamble.yaml
content: |
  다음 이메일의 중요도와 의사결정을 분석해주세요.

  반드시 아래 JSON 스키마로 응답하세요:
  {
    "summary": "메일 핵심 내용 요약 (50자 이내)",
    "importance": "매우 중요|중요|일반|낮음",
    "action": "즉시 답장 필요|답장 필요|참조만 해도 됨|아카이브",
    "reason": "분석 근거 (간단히)"
  }

  중요도 판단 기준:
  - 매우 중요: 긴급한 업무, 마감일, 중요한 의사결정
  - 중요: 업무 관련, 답장 필요, 후속 조치 필요
  - 일반: 정보 공유, 참고용, 일상적 업무
  - 낮음: 광고, 뉴스레터, 개인적 내용

  의사결정 기준:
  - 즉시 답장 필요: 긴급한 질문, 마감일, 중요한 요청
  - 답장 필요: 질문이나 요청이 있음, 업무 관련
  - 참조만 해도 됨: 정보 공유, 참고용
  - 아카이브: 광고, 불필요한 메일
