# -*- coding: utf-8 -*-
# CoordinatorAgent subtask templates. These are simple templates rendered with user_request.
# items[].content supports Python format placeholders like {user_request}.
items:
  - id_suffix: research
    type: research
    description: "사용자 요청에 관련된 정보 조사"
    content: "다음 주제에 대한 정보를 조사하세요: {user_request}"
    priority: medium
  - id_suffix: analysis
    type: analysis
    description: "정보 분석 및 인사이트 도출"
    content: "조사된 정보를 분석하고 핵심 인사이트를 도출하세요"
    priority: medium
    depends_on: [research]
