# -*- coding: utf-8 -*-
# TTS 프롬프트 프리앰블: 텍스트를 음성으로 변환할 때 적용되는 지침
content: |
  [TTS 지침]
  - 명료하고 자연스러운 억양으로 읽습니다.
  - 숫자/약어는 일반적인 한국어 읽기 관례에 맞춰 발음합니다.
  - 문장 사이 간단한 호흡을 둡니다.
  - 감정/톤은 본문 또는 페르소나 지침에 따릅니다.
